package cn.naiblog.carsearch.controller;

import cn.naiblog.carsearch.api.*;
import cn.naiblog.carsearch.security.AdminAuthInterceptor;
import cn.naiblog.carsearch.security.CryptoService;
import cn.naiblog.carsearch.security.CurrentAdmin;
import cn.naiblog.carsearch.service.*;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.*;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.*;

@RestController
@RequestMapping("/admin-api")
public class AdminOrderController {
    private final JdbcTemplate jdbc; private final CryptoService crypto; private final ObjectMapper mapper;
    private final PaymentReconciliationService payments; private final PaymentLifecycleService lifecycle; private final QueryRunnerService queries; private final AuditService audit;
    public AdminOrderController(JdbcTemplate jdbc,CryptoService crypto,ObjectMapper mapper,PaymentReconciliationService payments,PaymentLifecycleService lifecycle,QueryRunnerService queries,AuditService audit){this.jdbc=jdbc;this.crypto=crypto;this.mapper=mapper;this.payments=payments;this.lifecycle=lifecycle;this.queries=queries;this.audit=audit;}

    @GetMapping("/orders")
    public ApiResponse<Map<String,Object>>orders(@RequestParam(defaultValue="1")int page,@RequestParam(name="page_size",defaultValue="20")int size,@RequestParam(defaultValue="")String status,@RequestParam(defaultValue="")String keyword){
        page=Math.max(1,page);size=Math.max(1,Math.min(100,size));List<Object>args=new ArrayList<>();StringBuilder where=new StringBuilder(" where 1=1");if(!status.isBlank()){where.append(" and o.status=?");args.add(status);}if(!keyword.isBlank()){String like="%"+keyword.trim()+"%";where.append(" and (o.order_no like ? or p.order_no like ? or p.transaction_id like ? or p.wechat_order_id like ? or p.wechat_pay_transaction_id like ? or p.channel_order_id like ? or u.nickname like ? or u.phone like ?");for(int i=0;i<8;i++)args.add(like);if(keyword.matches("\\d+")){where.append(" or o.user_id=?");args.add(Long.parseLong(keyword));}where.append(")");}
        long total=scalar("select count(*) from ci_order o left join ci_user u on u.id=o.user_id left join ci_payment p on p.order_id=o.id"+where,args.toArray());List<Object>pageArgs=new ArrayList<>(args);pageArgs.add(size);pageArgs.add((page-1)*size);
        List<Map<String,Object>>rows=jdbc.queryForList("select o.id,o.order_no,o.user_id,o.service_name,o.amount,o.status,o.paid_at,o.queried_at,o.created_at,u.nickname,u.phone,p.wechat_order_type,p.wechat_order_id,p.wechat_pay_transaction_id,p.channel_order_id,p.delivery_status,p.delivery_attempts,p.delivery_last_error,p.delivered_at,p.refund_status,p.refund_source,p.refund_order_no,p.refund_amount,p.refund_reason,p.refund_from_status,p.refund_last_error,p.refund_requested_at,p.refunded_at from ci_order o left join ci_user u on u.id=o.user_id left join ci_payment p on p.order_id=o.id"+where+" order by o.id desc limit ? offset ?",pageArgs.toArray());
        rows.forEach(this::decorate);return ApiResponse.ok(Pagination.of(rows,total,page,size));
    }

    @GetMapping("/order-detail/{orderNo}")
    public ApiResponse<Map<String,Object>>detail(@PathVariable String orderNo){List<Map<String,Object>>rows=jdbc.queryForList("select o.*,u.nickname,u.phone,p.transaction_id,p.wechat_order_id,p.wechat_pay_transaction_id,p.channel_order_id,p.wechat_order_type,p.status payment_status,p.pay_env,p.callback_payload,p.last_checked_at,p.delivery_status,p.delivery_attempts,p.delivery_attempted_at,p.delivery_last_error,p.delivered_at,p.refund_status,p.refund_source,p.refund_order_no,p.refund_amount,p.refund_reason,p.refund_last_error,p.refund_requested_at,p.refunded_at from ci_order o left join ci_user u on u.id=o.user_id left join ci_payment p on p.order_id=o.id where o.order_no=?",orderNo);if(rows.isEmpty())throw new BusinessException(404,HttpStatus.NOT_FOUND,"订单不存在");Map<String,Object>row=rows.getFirst();row.put("input",decrypt(text(row.get("input_cipher")),"订单查询输入"));Map<String,Object>result=decrypt(text(row.get("result_cipher")),"订单查询结果");row.put("result",result.getOrDefault("items",List.of()));Map<String,Object>wx=jsonMap(text(row.get("callback_payload")));wx.remove("token");row.put("wechat_order",wx);row.put("refund_reason_label",refundReason(text(row.get("refund_reason"))));for(String k:List.of("input_cipher","result_cipher","service_snapshot_cipher","callback_payload"))row.remove(k);return ApiResponse.ok(row);}

    @PostMapping("/orders/{orderNo}/sync-payment") public ApiResponse<Map<String,Object>>sync(@PathVariable String orderNo,HttpServletRequest req){Map<String,Object>row=paymentOrder(orderNo);String current=text(row.get("status"));if(!Set.of("pending_payment","payment_review").contains(current))return ApiResponse.ok(Map.of("status",current),"订单状态无需同步");String state=payments.reconcile(row,row);if("paid".equals(state)){Map<String,Object>fresh=jdbc.queryForMap("select * from ci_order where order_no=?",orderNo);state=text(queries.run(fresh).get("status"));}audit.record(req,"order.payment.sync","order",orderNo,Map.of("status",state));return ApiResponse.ok(Map.of("status",state),"success".equals(state)?"支付已确认并完成查询":"微信支付状态已同步");}
    @PostMapping("/orders/{orderNo}/retry") public ApiResponse<Map<String,Object>>retry(@PathVariable String orderNo,HttpServletRequest req){Map<String,Object>result=queries.retry(orderNo);audit.record(req,"order.retry","order",orderNo,Map.of("status",result.get("status")));return ApiResponse.ok(result,"订单查询已重试");}
    @PostMapping("/orders/{orderNo}/delivery") public ApiResponse<Map<String,Object>>delivery(@PathVariable String orderNo,HttpServletRequest req){String state=lifecycle.deliver(orderNo,true);audit.record(req,"order.delivery.retry","order",orderNo,Map.of("status",state));return ApiResponse.ok(Map.of("status",state),"微信发货状态已确认");}
    @PostMapping("/orders/{orderNo}/refund") public ApiResponse<Map<String,Object>>refund(@PathVariable String orderNo,@RequestBody(required=false)Map<String,Object>b,HttpServletRequest req){String reason=b==null?"2":text(b.getOrDefault("reason","2"));String state=lifecycle.requestRefund(orderNo,reason);audit.record(req,"order.refund","order",orderNo,Map.of("reason",reason,"status",state));return ApiResponse.ok(Map.of("status",state),"refunded".equals(state)?"订单已退款":"退款申请已提交微信处理");}
    @PostMapping("/orders/{orderNo}/refund-status") public ApiResponse<Map<String,Object>>refundStatus(@PathVariable String orderNo,HttpServletRequest req){String state=lifecycle.reconcileRefund(orderNo);audit.record(req,"order.refund.reconcile","order",orderNo,Map.of("status",state));return ApiResponse.ok(Map.of("status",state),"refunded".equals(state)?"退款已完成":"failed".equals(state)?"退款失败，可重新申请":"退款仍在处理中");}
    @PostMapping("/orders/{orderNo}/manual-refund") public ApiResponse<Map<String,Object>>manualRefund(@PathVariable String orderNo,@RequestBody(required=false)Map<String,Object>b,HttpServletRequest req){List<Map<String,Object>>rows=jdbc.queryForList("select o.*,p.refund_status,p.wechat_order_type from ci_order o left join ci_payment p on p.order_id=o.id where o.order_no=?",orderNo);if(rows.isEmpty())throw new BusinessException("订单不存在");Map<String,Object>o=rows.getFirst();if(!Set.of("paid","query_failed","success").contains(text(o.get("status"))))throw new BusinessException("当前订单状态不允许退款");if(o.get("manual_refund_time")!=null)throw new BusinessException("该订单已登记手动退款");if(Set.of("requesting","processing","refunded","apple_review").contains(text(o.get("refund_status"))))throw new BusinessException("该订单已有线上退款记录，请勿重复操作");CurrentAdmin admin=(CurrentAdmin)req.getAttribute(AdminAuthInterceptor.ATTRIBUTE);String reason=b==null?"":text(b.get("reason"));String remark=cut("iOS 手动退款"+(reason.isBlank()?"":"，原因："+reason)+"，操作员："+admin.username(),255);LocalDateTime now=LocalDateTime.now();jdbc.update("update ci_order set status='refunded',manual_refund_amount=amount,manual_refund_time=?,manual_refund_remark=?,updated_at=? where id=?",now,remark,now,o.get("id"));audit.record(req,"order.manual_refund","order",orderNo,Map.of("amount",o.get("amount"),"reason",reason));return ApiResponse.ok(Map.of("status","refunded","amount",o.get("amount")),"手动退款已登记");}

    @PostMapping("/orders/batch-delete") @Transactional public ApiResponse<Object>deleteOrders(@RequestBody Map<String,Object>b,HttpServletRequest req){List<?>raw=b.get("order_nos")instanceof List<?>l?l:b.get("ids")instanceof List<?>l?l:List.of();List<String>nos=raw.stream().map(this::text).filter(v->!v.isBlank()).distinct().toList();if(nos.isEmpty())throw new BusinessException("请选择要删除的订单");if(nos.size()>200)throw new BusinessException("单次最多删除200笔订单");String marks=String.join(",",Collections.nCopies(nos.size(),"?"));List<Map<String,Object>>rows=jdbc.queryForList("select o.id,o.order_no,o.paid_at,p.status payment_status from ci_order o left join ci_payment p on p.order_id=o.id where o.order_no in ("+marks+")",nos.toArray());for(Map<String,Object>row:rows)if(row.get("paid_at")!=null||!Set.of("created","cancelled","").contains(text(row.get("payment_status"))))throw new BusinessException("已付款或进入支付处理的订单属于财务凭证，不能物理删除");for(Map<String,Object>row:rows){jdbc.update("delete from ci_payment where order_id=?",row.get("id"));jdbc.update("delete from ci_order where id=?",row.get("id"));}audit.record(req,"order.batch_delete","order",nos.getFirst(),Map.of("order_nos",nos,"count",rows.size()));return ApiResponse.ok(null,"已删除 "+rows.size()+" 笔订单");}

    @GetMapping("/wechat-messages") public ApiResponse<Map<String,Object>>messages(@RequestParam(defaultValue="1")int page,@RequestParam(name="page_size",defaultValue="20")int size,@RequestParam(defaultValue="")String type,@RequestParam(defaultValue="")String status){page=Math.max(1,page);size=Math.max(1,Math.min(100,size));List<Object>args=new ArrayList<>();StringBuilder where=new StringBuilder(" where 1=1");if(!type.isBlank()){where.append(" and event_type=?");args.add(type);}if(!status.isBlank()){where.append(" and process_status=?");args.add(status);}long total=scalar("select count(*) from ci_wechat_event"+where,args.toArray());List<Object>all=new ArrayList<>(args);all.add(size);all.add((page-1)*size);List<Map<String,Object>>rows=jdbc.queryForList("select * from ci_wechat_event"+where+" order by id desc limit ? offset ?",all.toArray());for(Map<String,Object>row:rows){Map<String,Object>request=crypto.decrypt(text(row.get("request_cipher"))),response=crypto.decrypt(text(row.get("response_cipher")));if(!text(row.get("request_cipher")).isBlank()&&request.isEmpty()&&row.get("last_error")==null)row.put("last_error","历史消息无法使用当前主密钥解密");row.put("summary",summary(text(row.get("event_type")),request));row.put("request",request);row.put("response",response);for(String k:List.of("request_cipher","response_cipher","event_key"))row.remove(k);}return ApiResponse.ok(Pagination.of(rows,total,page,size));}

    private Map<String,Object>paymentOrder(String no){List<Map<String,Object>>rows=jdbc.queryForList("select o.*,u.openid from ci_order o join ci_user u on u.id=o.user_id where o.order_no=?",no);if(rows.isEmpty())throw new BusinessException(404,HttpStatus.NOT_FOUND,"订单不存在");return rows.getFirst();}
    private void decorate(Map<String,Object>r){int type=number(r.get("wechat_order_type"),-1);r.put("payment_platform",type==7||type==8?"ios":type==0||type==1?"wechat":"unknown");String status=text(r.get("status"));r.put("fulfillment_status",Set.of("refunding","refunded").contains(status)?(!text(r.get("refund_from_status")).isBlank()?r.get("refund_from_status"):"delivered".equals(text(r.get("delivery_status")))?"success":"query_failed"):status);}
    private String summary(String type,Map<String,Object>p){String reason=text(first(p,"refund_request_reason","RefundRequestReason"));return switch(type){case"xpay_subscribe_ios_refund_query_notify"->"iOS 退款问询"+(reason.isBlank()?"":"："+refundReason(reason));case"xpay_refund_notify"->"退款结果："+(number(first(p,"RetCode","ret_code"),-1)==0?"成功":text(first(p,"RetMsg","ret_msg")));case"xpay_goods_deliver_notify"->"虚拟支付发货通知";case"xpay_coin_pay_notify"->"代币支付通知";case"xpay_complaint_notify"->"用户投诉："+cut(text(first(p,"ComplaintDetail","complaint_detail")),100);case"xpay_wxpay_callback_notify"->"微信支付风控通知："+cut(text(first(p,"Remark","remark")),100);default->"其他微信消息";};}
    private String refundReason(String r){return Map.of("UNINTENDED_PURCHASE","误操作购买","DID_NOT_MEAN_TO_BUY","误操作购买","ITEM_NOT_RECEIVED","未收到购买内容","ITEM_NOT_AS_DESCRIBED","内容与描述不符","QUALITY_ISSUE","质量问题","CHILD_PURCHASE","未成年人购买","OTHER","其他原因").getOrDefault(r.toUpperCase(Locale.ROOT),r);}
    private Map<String,Object>decrypt(String cipher,String label){if(cipher.isBlank())return Map.of();Map<String,Object>v=crypto.decrypt(cipher);if(v.isEmpty())throw new BusinessException(500,HttpStatus.INTERNAL_SERVER_ERROR,label+"无法解密，请检查服务器主加密密钥是否与原环境一致");return v;}
    private Map<String,Object>jsonMap(String json){if(json.isBlank())return new LinkedHashMap<>();try{return mapper.readValue(json,new TypeReference<LinkedHashMap<String,Object>>(){});}catch(Exception e){return new LinkedHashMap<>();}}
    private Object first(Map<String,Object>m,String...keys){for(String k:keys)if(m.containsKey(k))return m.get(k);return null;}private long scalar(String sql,Object...a){Long v=jdbc.queryForObject(sql,Long.class,a);return v==null?0:v;}private String text(Object v){return v==null?"":String.valueOf(v).trim();}private int number(Object v,int fallback){try{return v instanceof Number n?n.intValue():Integer.parseInt(text(v));}catch(Exception e){return fallback;}}private String cut(String v,int n){return v==null?"":v.length()<=n?v:v.substring(0,n);}
}
