package cn.naiblog.carsearch.controller;

import cn.naiblog.carsearch.api.*;
import cn.naiblog.carsearch.config.SettingService;
import cn.naiblog.carsearch.security.*;
import cn.naiblog.carsearch.service.AuditService;
import cn.naiblog.carsearch.service.MailService;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.security.SecureRandom;
import java.time.*;
import java.time.format.DateTimeParseException;
import java.util.*;
import java.util.regex.Pattern;

@RestController
@RequestMapping("/admin-api")
public class AdminController {
    private static final Pattern APP_ID=Pattern.compile("^wx[A-Za-z0-9]{16}$");
    private static final Pattern OFFER_ID=Pattern.compile("^[A-Za-z0-9_-]{1,64}$");
    private static final Pattern EMAIL=Pattern.compile("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$");
    private final JdbcTemplate jdbc; private final SettingService settings; private final AuditService audit; private final MailService mail;
    private final BCryptPasswordEncoder bcrypt=new BCryptPasswordEncoder(); private final SecureRandom random=new SecureRandom();
    public AdminController(JdbcTemplate jdbc,SettingService settings,AuditService audit,MailService mail){this.jdbc=jdbc;this.settings=settings;this.audit=audit;this.mail=mail;}

    @PostMapping("/login")
    public ApiResponse<Map<String,Object>>login(@RequestBody Map<String,Object>b,HttpServletRequest req){
        String username=text(b.get("username")); String identity=Hashing.sha256(username.toLowerCase(Locale.ROOT)+"|"+req.getRemoteAddr());
        List<Map<String,Object>>attempts=jdbc.queryForList("select * from ci_admin_login_attempt where identity_hash=?",identity);
        if(!attempts.isEmpty()&&future(attempts.getFirst().get("locked_until")))throw new BusinessException(429,HttpStatus.TOO_MANY_REQUESTS,"登录尝试过多，请15分钟后再试");
        List<Map<String,Object>>rows=jdbc.queryForList("select * from ci_admin where username=? and status=1",username);
        if(rows.isEmpty()||!bcrypt.matches(text(b.get("password")),text(rows.getFirst().get("password_hash")))){
            int count=attempts.isEmpty()?1:number(attempts.getFirst().get("fail_count"))+1; LocalDateTime now=LocalDateTime.now();
            jdbc.update("insert into ci_admin_login_attempt(identity_hash,fail_count,locked_until,updated_at) values(?,?,?,?) on duplicate key update fail_count=values(fail_count),locked_until=values(locked_until),updated_at=values(updated_at)",identity,count>=5?0:count,count>=5?now.plusMinutes(15):null,now);
            throw new BusinessException(401,HttpStatus.UNAUTHORIZED,"账号或密码错误");
        }
        Map<String,Object>admin=rows.getFirst(); jdbc.update("delete from ci_admin_login_attempt where identity_hash=?",identity);
        byte[] bytes=new byte[32];random.nextBytes(bytes);String token=HexFormat.of().formatHex(bytes);LocalDateTime now=LocalDateTime.now();
        jdbc.update("insert into ci_admin_token(admin_id,token_hash,expires_at,created_at) values(?,?,?,?)",admin.get("id"),Hashing.sha256(token),now.plusHours(8),now);
        jdbc.update("update ci_admin set last_login_at=?,updated_at=? where id=?",now,now,admin.get("id"));
        return ApiResponse.ok(Map.of("token",token,"admin",Map.of("id",admin.get("id"),"username",admin.get("username"),"must_change_password",number(admin.get("must_change_password"))!=0)));
    }

    @GetMapping("/dashboard") public ApiResponse<Map<String,Object>> dashboard(){
        LocalDate today=LocalDate.now(); Map<String,Object>trend=new LinkedHashMap<>();List<String>dates=new ArrayList<>();List<Long>orders=new ArrayList<>();List<BigDecimal>sales=new ArrayList<>();List<BigDecimal>profit=new ArrayList<>();
        for(int i=13;i>=0;i--){LocalDate d=today.minusDays(i);LocalDateTime a=d.atStartOfDay(),z=d.plusDays(1).atStartOfDay();dates.add(d.toString().substring(5));orders.add(scalar("select count(*) from ci_order where created_at>=? and created_at<?",a,z));BigDecimal s=decimal("select coalesce(sum(amount),0) from ci_order where paid_at>=? and paid_at<?",a,z),c=decimal("select coalesce(sum(cost_amount),0) from ci_order where queried_at>=? and queried_at<?",a,z);sales.add(s);profit.add(s.subtract(c));}
        trend.put("dates",dates);trend.put("orders",orders);trend.put("sales",sales);trend.put("profit",profit);
        Map<String,Object> periods=new LinkedHashMap<>();periods.put("today",stats(today.atStartOfDay(),null));periods.put("yesterday",stats(today.minusDays(1).atStartOfDay(),today.atStartOfDay()));periods.put("month",stats(today.withDayOfMonth(1).atStartOfDay(),null));periods.put("total",stats(null,null));
        Map<String,String> labels=Map.of("pending_payment","待付款","payment_review","待核对","paid","待查询","querying","查询中","success","查询成功","query_failed","查询异常","refunding","退款处理中","cancelled","已取消","refunded","已退款");
        List<Map<String,Object>>status=jdbc.queryForList("select status name,count(*) value from ci_order group by status");status.forEach(r->r.put("name",labels.getOrDefault(text(r.get("name")),text(r.get("name")))));
        Map<String,Object> result=new LinkedHashMap<>();result.put("users",scalar("select count(*) from ci_user"));result.put("total_orders",scalar("select count(*) from ci_order"));result.put("failed_orders",scalar("select count(*) from ci_order where status='query_failed'"));result.put("pending_orders",scalar("select count(*) from ci_order where status in ('pending_payment','payment_review','paid','querying','refunding')"));result.put("today_paid_orders",scalar("select count(*) from ci_order where paid_at>=?",today.atStartOfDay()));result.put("periods",periods);result.put("trend",trend);result.put("service_distribution",jdbc.queryForList("select service_name name,count(*) value from ci_order group by service_name order by value desc limit 8"));result.put("status_distribution",status);return ApiResponse.ok(result);
    }

    @GetMapping("/dashboard-finance") public ApiResponse<Map<String,Object>> finance(@RequestParam(required=false)String start,@RequestParam(required=false)String end){
        LocalDate to=parseDate(end,LocalDate.now()),from=parseDate(start,to.minusDays(6));if(from.isAfter(to)||Duration.between(from.atStartOfDay(),to.plusDays(1).atStartOfDay()).toDays()>366)throw new BusinessException("日期范围无效或超过366天");
        List<String>dates=new ArrayList<>();List<BigDecimal>net=new ArrayList<>(),refunds=new ArrayList<>(),profit=new ArrayList<>(),cost=new ArrayList<>();
        for(LocalDate d=from;!d.isAfter(to);d=d.plusDays(1)){LocalDateTime a=d.atStartOfDay(),z=d.plusDays(1).atStartOfDay();BigDecimal sales=decimal("select coalesce(sum(amount),0) from ci_order where paid_at>=? and paid_at<?",a,z);BigDecimal online=decimal("select coalesce(sum(refund_amount),0) from ci_payment where refunded_at>=? and refunded_at<?",a,z);BigDecimal manual=decimal("select coalesce(sum(manual_refund_amount),0) from ci_order where manual_refund_time is not null and paid_at>=? and paid_at<?",a,z);BigDecimal c=decimal("select coalesce(sum(cost_amount),0) from ci_order where queried_at>=? and queried_at<?",a,z);BigDecimal r=online.add(manual);dates.add(d.toString().substring(5));net.add(sales);refunds.add(r);cost.add(c);profit.add(sales.subtract(r).subtract(c));}
        return ApiResponse.ok(Map.of("start",from.toString(),"end",to.toString(),"dates",dates,"net",net,"refunds",refunds,"cost",cost,"profit",profit));
    }

    @GetMapping("/users") public ApiResponse<Map<String,Object>>users(@RequestParam(defaultValue="1")int page,@RequestParam(name="page_size",defaultValue="20")int size,@RequestParam(defaultValue="")String keyword){
        page=Math.max(1,page);size=Math.max(1,Math.min(100,size));String like="%"+keyword.trim()+"%";boolean search=!keyword.isBlank();String where=search?" where nickname like ? or phone like ?"+(keyword.matches("\\d+")?" or id=?":""):"";List<Object>args=new ArrayList<>();if(search){args.add(like);args.add(like);if(keyword.matches("\\d+"))args.add(Long.parseLong(keyword));}long total=scalar("select count(*) from ci_user"+where,args.toArray());args.add(size);args.add((page-1)*size);return ApiResponse.ok(Pagination.of(jdbc.queryForList("select id,nickname,avatar_url,phone,status,last_login_at,created_at from ci_user"+where+" order by id desc limit ? offset ?",args.toArray()),total,page,size));
    }
    @PostMapping("/users/{id}/status") public ApiResponse<Object>userStatus(@PathVariable long id,@RequestBody Map<String,Object>b,HttpServletRequest req){int status=number(b.getOrDefault("status",1));if(status!=0&&status!=1)throw new BusinessException("状态无效");jdbc.update("update ci_user set status=?,updated_at=? where id=?",status,LocalDateTime.now(),id);audit.record(req,"user.status","user",String.valueOf(id),Map.of("status",status));return ApiResponse.ok(null,"用户状态已更新");}

    @GetMapping("/announcements") public ApiResponse<List<Map<String,Object>>>announcements(){return ApiResponse.ok(jdbc.queryForList("select * from ci_announcement order by id desc"));}
    @PostMapping("/announcements") public ApiResponse<Map<String,Object>>announcement(@RequestBody Map<String,Object>b,HttpServletRequest req){String title=text(b.get("title")),content=text(b.get("content"));if(title.isBlank()||content.isBlank())throw new BusinessException("标题和内容不能为空");LocalDateTime now=LocalDateTime.now();int id=number(b.get("id"));Object start=blankToNull(text(b.get("start_at"))),end=blankToNull(text(b.get("end_at")));if(id>0)jdbc.update("update ci_announcement set title=?,content=?,suppress_hours=?,status=?,start_at=?,end_at=?,updated_at=? where id=?",cut(title,100),content,clamp(number(b.getOrDefault("suppress_hours",24)),1,720),number(b.getOrDefault("status",1)),start,end,now,id);else{jdbc.update("insert into ci_announcement(title,content,suppress_hours,status,start_at,end_at,created_at,updated_at) values(?,?,?,?,?,?,?,?)",cut(title,100),content,clamp(number(b.getOrDefault("suppress_hours",24)),1,720),number(b.getOrDefault("status",1)),start,end,now,now);id=jdbc.queryForObject("select last_insert_id()",Integer.class);}audit.record(req,"announcement.save","announcement",String.valueOf(id),Map.of());return ApiResponse.ok(Map.of("id",id),"公告已保存");}

    @GetMapping("/settings") public ApiResponse<Map<String,String>>getSettings(){Map<String,String>r=new LinkedHashMap<>();jdbc.query("select `key`,value from ci_setting",rs->{while(rs.next())r.put(rs.getString(1),rs.getString(2));});return ApiResponse.ok(r);}
    @PostMapping("/settings") public ApiResponse<Object>saveSettings(@RequestBody Map<String,Object>b,HttpServletRequest req){Map<String,Object>values=map(b.getOrDefault("settings",b));Set<String>allowed=Set.of("operator_name","privacy_contact","privacy_effective_date","customer_service_phone","customer_service_hours","disclaimer","privacy_retention_days");if(text(values.get("operator_name")).isBlank()||text(values.get("operator_name")).length()>120)throw new BusinessException("请填写不超过120字的运营主体全称");if(text(values.get("privacy_contact")).isBlank()||text(values.get("privacy_contact")).length()>120)throw new BusinessException("请填写不超过120字的个人信息保护联系方式");if(!text(values.get("privacy_effective_date")).matches("\\d{4}-\\d{2}-\\d{2}"))throw new BusinessException("隐私规则生效日期格式不正确");int days=number(values.get("privacy_retention_days"));if(days<1||days>365)throw new BusinessException("查询数据保留天数需在1至365天之间");for(String k:allowed)if(values.containsKey(k))settings.saveValue(k,text(values.get(k)));audit.record(req,"settings.save","setting","",values.keySet());return ApiResponse.ok(null,"设置已保存");}

    @GetMapping("/payment-settings") public ApiResponse<Map<String,Object>>paymentSettings(){var c=settings.wechat();Map<String,Object>r=new LinkedHashMap<>();r.put("payment_enabled",settings.value("payment_enabled","0"));r.put("wechat_app_id",c.appId());r.put("wechat_offer_id",c.offerId());r.put("wechat_pay_env",c.payEnv());r.put("app_secret_configured",!c.appSecret().isBlank());r.put("sandbox_app_key_configured",!c.sandboxAppKey().isBlank());r.put("production_app_key_configured",!c.productionAppKey().isBlank());r.put("message_token_configured",configured("wechat_message_token"));r.put("message_aes_key_configured",configured("wechat_message_aes_key"));r.put("ios_refund_reject_result_info",settings.value("ios_refund_reject_result_info","订单已完成服务交付，建议不予退款"));r.put("ios_refund_reject_evidence",settings.value("ios_refund_reject_evidence","业务订单 {order_no} 已于 {delivered_at} 完成查询并向微信确认发货。"));r.put("ios_refund_approve_result_info",settings.value("ios_refund_approve_result_info","未能确认服务已经完整交付，建议退款"));r.put("ios_refund_approve_evidence",settings.value("ios_refund_approve_evidence","{decision_reason}，业务订单 {order_no}。"));r.put("message_callback_path","/wechat/message");return ApiResponse.ok(r);}
    @PostMapping("/payment-settings") public ApiResponse<Object>savePayment(@RequestBody Map<String,Object>b,HttpServletRequest req){String appId=text(b.get("wechat_app_id")),offer=text(b.get("wechat_offer_id"));int env=number(b.getOrDefault("wechat_pay_env",0));boolean enabled="1".equals(text(b.get("payment_enabled")));if(!appId.isBlank()&&!APP_ID.matcher(appId).matches())throw new BusinessException("微信 AppID 格式不正确");if(!offer.isBlank()&&!OFFER_ID.matcher(offer).matches())throw new BusinessException("OfferID 格式不正确");if(env!=0&&env!=1)throw new BusinessException("支付环境无效");if(!appId.isBlank())settings.saveValue("wechat_app_id",appId);if(!offer.isBlank())settings.saveValue("wechat_offer_id",offer);settings.saveValue("wechat_pay_env",String.valueOf(env));List<String>updated=new ArrayList<>();for(String k:List.of("wechat_app_secret","wechat_sandbox_app_key","wechat_production_app_key","wechat_message_token","wechat_message_aes_key")){String v=text(b.get(k));if(!v.isBlank()){if(k.endsWith("message_token")&&!v.matches("[A-Za-z0-9]{3,32}"))throw new BusinessException("消息推送 Token 需为3至32位字母或数字");if(k.endsWith("message_aes_key")&&!v.matches("[A-Za-z0-9]{43}"))throw new BusinessException("消息推送 EncodingAESKey 必须是43位字符串");settings.saveSecure(k,v);updated.add(k);}}Map<String,Integer>limits=Map.of("ios_refund_reject_result_info",200,"ios_refund_reject_evidence",1000,"ios_refund_approve_result_info",200,"ios_refund_approve_evidence",1000);for(var entry:limits.entrySet()){String v=text(b.get(entry.getKey()));if(v.isBlank()||v.length()>entry.getValue())throw new BusinessException("iOS 退款回复内容不能为空或超过长度限制");settings.saveValue(entry.getKey(),v);}settings.saveSecure("wechat_access_token","");settings.saveValue("wechat_access_token_expires_at","0");var c=settings.wechat();if(enabled&&(c.appId().isBlank()||c.appSecret().isBlank()||c.offerId().isBlank()||c.appKey().isBlank()||!configured("wechat_message_token")||!configured("wechat_message_aes_key"))){settings.saveValue("payment_enabled","0");throw new BusinessException("配置尚不完整：必须同时配置支付参数与微信消息推送参数");}settings.saveValue("payment_enabled",enabled?"1":"0");audit.record(req,"payment.settings.save","setting","payment",Map.of("payment_enabled",enabled,"wechat_app_id",appId,"wechat_offer_id",offer,"wechat_pay_env",env,"updated_secrets",updated));return ApiResponse.ok(null,"支付配置已安全保存");}

    @GetMapping("/email-settings") public ApiResponse<Map<String,Object>>emailSettings(){Map<String,Object>r=new LinkedHashMap<>();for(String k:List.of("smtp_host","smtp_port","smtp_encryption","smtp_username","smtp_from_address","smtp_from_name","email_notify_daily","email_notify_payment","email_notify_query_success","email_notify_query_failed","email_recipients"))r.put(k,settings.value(k,Map.of("smtp_port","465","smtp_encryption","ssl").getOrDefault(k,"")));r.put("smtp_password_configured",configured("smtp_password"));return ApiResponse.ok(r);}
    @PostMapping("/email-settings") public ApiResponse<Object>saveEmail(@RequestBody Map<String,Object>b,HttpServletRequest req){String host=text(b.get("smtp_host")),encryption=text(b.getOrDefault("smtp_encryption","ssl")).toLowerCase(Locale.ROOT),from=text(b.get("smtp_from_address")),recipients=text(b.get("email_recipients"));int port=number(b.getOrDefault("smtp_port",465));if(host.length()>200||port<1||port>65535||!Set.of("ssl","tls","none").contains(encryption))throw new BusinessException("SMTP 服务器、端口或加密方式无效");if(!from.isBlank()&&!EMAIL.matcher(from).matches())throw new BusinessException("发件人邮箱格式不正确");for(String email:recipients.split("[,;\\r\\n]+"))if(!email.isBlank()&&!EMAIL.matcher(email.trim()).matches())throw new BusinessException("收件人邮箱格式不正确："+email);for(String k:List.of("smtp_host","smtp_port","smtp_encryption","smtp_username","smtp_from_address","smtp_from_name","email_notify_daily","email_notify_payment","email_notify_query_success","email_notify_query_failed","email_recipients"))settings.saveValue(k,switch(k){case"smtp_port"->String.valueOf(port);case"smtp_encryption"->encryption;case"email_notify_daily","email_notify_payment","email_notify_query_success","email_notify_query_failed"->"1".equals(text(b.get(k)))?"1":"0";default->text(b.get(k));});String password=text(b.get("smtp_password"));if(!password.isBlank())settings.saveSecure("smtp_password",password);audit.record(req,"email.settings.save","setting","email",b.keySet());return ApiResponse.ok(null,"邮件配置已保存");}
    @PostMapping("/email-test") public ApiResponse<Object>testEmail(HttpServletRequest req){if(!mail.available()||mail.recipients().isEmpty())throw new BusinessException("请先完整配置 SMTP 信息和收件人邮箱");try{mail.testConnection();List<String>sent=new ArrayList<>();for(String to:mail.recipients()){mail.send(to,"SMTP 测试邮件 - "+LocalDateTime.now(),mail.testTemplate());sent.add(to);}audit.record(req,"email.test","setting","email",Map.of("sent",sent));return ApiResponse.ok(null,"测试邮件已发送至 "+String.join("、",sent));}catch(Exception e){throw new BusinessException("SMTP 连接或发送失败："+cut(e.getMessage(),300));}}
    @PostMapping("/password") public ApiResponse<Object>password(@RequestBody Map<String,Object>b,HttpServletRequest req){CurrentAdmin a=(CurrentAdmin)req.getAttribute(AdminAuthInterceptor.ATTRIBUTE);Map<String,Object>row=jdbc.queryForMap("select password_hash from ci_admin where id=?",a.id());if(!bcrypt.matches(text(b.get("old_password")),text(row.get("password_hash"))))throw new BusinessException("原密码错误");String p=text(b.get("new_password"));int groups=(p.matches(".*[a-z].*")?1:0)+(p.matches(".*[A-Z].*")?1:0)+(p.matches(".*\\d.*")?1:0)+(p.matches(".*[^A-Za-z0-9].*")?1:0);if(p.length()<12||p.length()>128||groups<3)throw new BusinessException("新密码需为12至128位，并至少包含四类字符中的三类");jdbc.update("update ci_admin set password_hash=?,must_change_password=0,updated_at=? where id=?",bcrypt.encode(p),LocalDateTime.now(),a.id());jdbc.update("delete from ci_admin_token where admin_id=?",a.id());return ApiResponse.ok(null,"密码已修改，请重新登录");}
    @PostMapping("/logout") public ApiResponse<Object>logout(HttpServletRequest req){String auth=req.getHeader("Authorization");if(auth!=null&&auth.regionMatches(true,0,"Bearer ",0,7))jdbc.update("delete from ci_admin_token where token_hash=?",Hashing.sha256(auth.substring(7).trim()));return ApiResponse.ok(null,"已安全退出");}

    private Map<String,Object>stats(LocalDateTime start,LocalDateTime end){String between=start==null?"":end==null?" and %s>=?":" and %s>=? and %s<?";List<Object>args=start==null?List.of():end==null?List.of(start):List.of(start,end);long orders=scalar("select count(*) from ci_order where 1=1"+between.formatted("created_at","created_at"),args.toArray());BigDecimal sales=decimal("select coalesce(sum(amount),0) from ci_order where 1=1"+between.formatted("paid_at","paid_at"),args.toArray()),refund=decimal("select coalesce(sum(refund_amount),0) from ci_payment where 1=1"+between.formatted("refunded_at","refunded_at"),args.toArray()),manual=decimal("select coalesce(sum(manual_refund_amount),0) from ci_order where manual_refund_time is not null"+between.formatted("paid_at","paid_at"),args.toArray()),cost=decimal("select coalesce(sum(cost_amount),0) from ci_order where 1=1"+between.formatted("queried_at","queried_at"),args.toArray());BigDecimal totalRefund=refund.add(manual);return Map.of("orders",orders,"revenue",sales,"refunds",totalRefund,"cost",cost,"profit",sales.subtract(totalRefund).subtract(cost));}
    private boolean configured(String k){try{return !settings.secure(k,"").isBlank();}catch(Exception e){return false;}}private boolean future(Object v){return v instanceof java.sql.Timestamp t&&t.toLocalDateTime().isAfter(LocalDateTime.now());}private LocalDate parseDate(String v,LocalDate fallback){try{return v==null||v.isBlank()?fallback:LocalDate.parse(v);}catch(DateTimeParseException e){return fallback;}}private long scalar(String sql,Object...a){Long v=jdbc.queryForObject(sql,Long.class,a);return v==null?0:v;}private BigDecimal decimal(String sql,Object...a){BigDecimal v=jdbc.queryForObject(sql,BigDecimal.class,a);return v==null?BigDecimal.ZERO:v;}private String text(Object v){return v==null?"":String.valueOf(v).trim();}private int number(Object v){try{return v instanceof Number n?n.intValue():Integer.parseInt(text(v));}catch(Exception e){return 0;}}private int clamp(int v,int a,int b){return Math.max(a,Math.min(b,v));}private String cut(String v,int n){if(v==null)return"";return v.length()<=n?v:v.substring(0,n);}@SuppressWarnings("unchecked")private Map<String,Object>map(Object v){return v instanceof Map<?,?>m?(Map<String,Object>)m:Map.of();}private Object blankToNull(String v){return v.isBlank()?null:v;}
}
