package cn.naiblog.carsearch.service;

import cn.naiblog.carsearch.api.BusinessException;
import cn.naiblog.carsearch.wechat.WechatPaymentService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.ObjectMapper;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
public class PaymentLifecycleService {
    private static final Set<String> REFUNDABLE=Set.of("paid","query_failed","success");
    private final JdbcTemplate jdbc; private final WechatPaymentService wechat; private final PaymentReconciliationService payments; private final QueryRunnerService queries; private final PaymentDeliveryService delivery; private final ObjectMapper mapper;private final TransactionTemplate transaction;
    public PaymentLifecycleService(JdbcTemplate jdbc,WechatPaymentService wechat,PaymentReconciliationService payments,QueryRunnerService queries,PaymentDeliveryService delivery,ObjectMapper mapper,PlatformTransactionManager transactionManager){this.jdbc=jdbc;this.wechat=wechat;this.payments=payments;this.queries=queries;this.delivery=delivery;this.mapper=mapper;this.transaction=new TransactionTemplate(transactionManager);}

    public String deliver(String orderNo,boolean throwOnFailure){return delivery.deliver(orderNo,throwOnFailure);}

    public String requestRefund(String orderNo,String reason){if(!Set.of("0","1","2","3","4","5").contains(reason))throw new BusinessException("退款原因无效");Map<String,Object>r=row(orderNo);if("refunded".equals(r.get("refund_status"))||"refunded".equals(r.get("order_status")))return"refunded";if(Set.of("requesting","processing","apple_review").contains(string(r,"refund_status"))||"refunding".equals(r.get("order_status")))return reconcileRefund(orderNo);if(!REFUNDABLE.contains(string(r,"order_status")))throw new BusinessException("当前订单状态不允许退款");if(number(r,"wechat_order_type")==7)throw new BusinessException("iOS 订单由用户向 Apple 申请退款，开发者不能主动退款或以转账代替；系统会通过微信退款问询和退款成功通知自动同步结果");Map<String,Object>w=wechat.queryOrder(string(r,"openid"),orderNo,number(r,"pay_env"));if(Set.of(5,8).contains(number(w,"status"))){markRefunded(r,w);return"refunded";}if(number(w,"order_type")==7)throw new BusinessException("Apple 支付不支持开发者主动退款，请用户前往 App Store 申请退款");if(!Set.of(2,3,4).contains(number(w,"status")))throw new BusinessException("微信订单当前状态不允许退款");int left=number(w,"left_fee");if(left<=0)left=number(w,"paid_fee");if(left<=0)left=number(w,"order_fee");if(left<=0)throw new BusinessException("退款金额无效");String refundNo=string(r,"refund_order_no");if(refundNo.isBlank())refundNo="R"+LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+String.format("%08d",number(r,"payment_id"));LocalDateTime now=LocalDateTime.now();String finalRefundNo=refundNo;int finalLeft=left;transaction.executeWithoutResult(tx->{int changed=jdbc.update("update ci_order set status='refunding',updated_at=? where id=? and status=?",now,r.get("order_id"),r.get("order_status"));if(changed==0)throw new BusinessException("订单状态已变化，请刷新后重试");jdbc.update("update ci_payment set refund_order_no=?,refund_status='requesting',refund_amount=?,refund_reason=?,refund_from_status=?,refund_requested_at=?,refund_last_error=null,updated_at=? where id=?",finalRefundNo,new BigDecimal(finalLeft).movePointLeft(2),reason,r.get("order_status"),now,now,r.get("payment_id"));});
        try{wechat.refund(string(r,"openid"),orderNo,refundNo,left,left,reason,number(r,"pay_env"));jdbc.update("update ci_payment set status='refund_processing',refund_status='processing',updated_at=? where id=?",now,r.get("payment_id"));return"processing";}catch(Exception e){String msg=truncate(e.getMessage(),500);if(msg.startsWith("微信支付接口调用失败：")){markRefundFailed(r,msg);throw new BusinessException("微信退款申请失败："+msg);}jdbc.update("update ci_payment set refund_last_error=?,updated_at=? where id=?",msg,LocalDateTime.now(),r.get("payment_id"));return"processing";}}

    public String reconcileRefund(String orderNo){Map<String,Object>r=row(orderNo);if("refunded".equals(r.get("refund_status"))||"refunded".equals(r.get("order_status")))return"refunded";Map<String,Object>w;if("apple_review".equals(r.get("refund_status"))){w=wechat.queryOrder(string(r,"openid"),orderNo,number(r,"pay_env"));jdbc.update("update ci_payment set last_checked_at=? where id=?",LocalDateTime.now(),r.get("payment_id"));if(Set.of(5,8).contains(number(w,"status"))){markRefunded(r,w);return"refunded";}if(number(w,"status")==7){markRefundFailed(r,"Apple 未批准本次退款");return"failed";}return"processing";}String refundNo=string(r,"refund_order_no");if(refundNo.isBlank())throw new BusinessException("订单尚未发起退款");try{w=wechat.queryOrder(string(r,"openid"),refundNo,number(r,"pay_env"));if(Boolean.TRUE.equals(w.get("not_found")))throw new IllegalStateException("微信退款单尚未创建");}catch(Exception refundQueryError){if("requesting".equals(string(r,"refund_status"))){int refundFee=cents(r.get("refund_amount"));if(refundFee<=0)refundFee=cents(r.get("amount"));try{Map<String,Object>payOrder=wechat.queryOrder(string(r,"openid"),orderNo,number(r,"pay_env"));int leftFee=number(payOrder,"left_fee");if(leftFee<=0||refundFee>leftFee)throw new IllegalStateException("微信订单剩余可退金额不足");wechat.refund(string(r,"openid"),orderNo,refundNo,leftFee,refundFee,string(r,"refund_reason").isBlank()?"2":string(r,"refund_reason"),number(r,"pay_env"));jdbc.update("update ci_payment set status='refund_processing',refund_status='processing',refund_last_error=null,updated_at=? where id=?",LocalDateTime.now(),r.get("payment_id"));}catch(Exception submitError){String message=truncate(submitError.getMessage(),500);if(message.startsWith("微信支付接口调用失败：")){markRefundFailed(r,message);return"failed";}jdbc.update("update ci_payment set refund_last_error=?,updated_at=? where id=?",message,LocalDateTime.now(),r.get("payment_id"));}return"processing";}w=wechat.queryOrder(string(r,"openid"),orderNo,number(r,"pay_env"));}
        int status=number(w,"status");if(Set.of(5,8).contains(status)){markRefunded(r,w);return"refunded";}if(status==7){markRefundFailed(r,"微信退款处理失败");try{jdbc.update("update ci_payment set refund_payload=? where id=?",truncate(mapper.writeValueAsString(w),60000),r.get("payment_id"));}catch(Exception ignored){}return"failed";}return"processing";}

    public Map<String,Integer> reconcilePending(int requestedLimit){int limit=Math.max(1,Math.min(200,requestedLimit));List<Map<String,Object>>payRows=jdbc.queryForList("select o.*,u.openid from ci_order o join ci_user u on u.id=o.user_id join ci_payment p on p.order_id=o.id where o.status in ('pending_payment','payment_review') and o.created_at<? and o.created_at>=? order by coalesce(p.last_checked_at,'1970-01-01') limit ?",LocalDateTime.now().minusSeconds(20),LocalDateTime.now().minusDays(2),limit);int paid=0,queried=0;for(Map<String,Object>o:payRows)try{if("paid".equals(payments.reconcile(o,o))){paid++;Map<String,Object>fresh=jdbc.queryForMap("select * from ci_order where id=?",o.get("id"));if("success".equals(queries.run(fresh).get("status")))queried++;}}catch(Exception ignored){}LocalDateTime stale=LocalDateTime.now().minusMinutes(5);List<Map<String,Object>>staleRows=jdbc.queryForList("select * from ci_order where status='querying' and updated_at<? limit ?",stale,limit);int recovered=0;for(Map<String,Object>o:staleRows)try{if(jdbc.update("update ci_order set status='paid',updated_at=? where id=? and status='querying' and updated_at<?",LocalDateTime.now(),o.get("id"),stale)>0&&"success".equals(queries.run(jdbc.queryForMap("select * from ci_order where id=?",o.get("id"))).get("status")))recovered++;}catch(Exception ignored){}List<Map<String,Object>>delivery=jdbc.queryForList("select p.order_no from ci_payment p join ci_order o on o.id=p.order_id where o.status='success' and (p.delivery_status in ('pending','failed') or (p.delivery_status='processing' and p.delivery_attempted_at<?)) limit ?",stale,limit);int delivered=0;for(Map<String,Object>o:delivery)if("delivered".equals(deliver(string(o,"order_no"),false)))delivered++;List<Map<String,Object>>refunds=jdbc.queryForList("select order_no from ci_payment where refund_status in ('requesting','processing','apple_review') order by coalesce(last_checked_at,'1970-01-01') limit ?",limit);int refunded=0;for(Map<String,Object>o:refunds)try{if("refunded".equals(reconcileRefund(string(o,"order_no"))))refunded++;}catch(Exception ignored){}return Map.of("payment_checked",payRows.size(),"paid",paid,"queried",queried,"recovered",recovered,"delivery_checked",delivery.size(),"delivered",delivered,"refund_checked",refunds.size(),"refunded",refunded);}

    private Map<String,Object>row(String no){List<Map<String,Object>>rows=jdbc.queryForList("select o.id order_id,o.order_no,o.status order_status,o.amount,o.user_id,p.id payment_id,p.status payment_status,p.pay_env,p.delivery_status,p.delivery_attempts,p.delivery_attempted_at,p.refund_order_no,p.refund_status,p.refund_source,p.refund_amount,p.refund_reason,p.refund_from_status,p.refund_requested_at,p.wechat_order_type,u.openid from ci_order o join ci_payment p on p.order_id=o.id join ci_user u on u.id=o.user_id where o.order_no=?",no);if(rows.isEmpty())throw new BusinessException("订单不存在");return rows.getFirst();}
    private void markRefundFailed(Map<String,Object>r,String msg){String restore=REFUNDABLE.contains(string(r,"refund_from_status"))?string(r,"refund_from_status"):REFUNDABLE.contains(string(r,"order_status"))?string(r,"order_status"):"query_failed";LocalDateTime now=LocalDateTime.now();transaction.executeWithoutResult(tx->{jdbc.update("update ci_order set status=?,updated_at=? where id=? and status='refunding'",restore,now,r.get("order_id"));jdbc.update("update ci_payment set status='paid',refund_status='failed',refund_last_error=?,updated_at=? where id=?",truncate(msg,500),now,r.get("payment_id"));});}
    private void markRefunded(Map<String,Object>r,Map<String,Object>w){LocalDateTime now=LocalDateTime.now();BigDecimal amount=r.get("refund_amount") instanceof BigDecimal b?b:new BigDecimal(number(w,"refund_fee")>0?number(w,"refund_fee"):new BigDecimal(string(r,"amount")).movePointRight(2).intValue()).movePointLeft(2);try{String payload=truncate(mapper.writeValueAsString(w),60000);transaction.executeWithoutResult(tx->{jdbc.update("update ci_order set status='refunded',updated_at=? where id=?",now,r.get("order_id"));jdbc.update("update ci_payment set status='refunded',refund_status='refunded',refund_source=coalesce(refund_source,?),refund_amount=?,refund_payload=?,refunded_at=?,refund_last_error=null,updated_at=? where id=?",number(r,"wechat_order_type")==7?"apple":"wechat",amount,payload,now,now,r.get("payment_id"));});}catch(Exception e){throw new IllegalStateException(e);}}
    private String string(Map<String,Object>m,String k){Object v=m.get(k);return v==null?"":String.valueOf(v);}private int number(Map<String,Object>m,String k){Object v=m.get(k);if(v instanceof Number n)return n.intValue();try{return Integer.parseInt(String.valueOf(v));}catch(Exception e){return 0;}}private LocalDateTime localDateTime(Object v){return v instanceof java.sql.Timestamp t?t.toLocalDateTime():v instanceof LocalDateTime d?d:null;}private String truncate(String s,int n){if(s==null)return"";return s.length()<=n?s:s.substring(0,n);}
    private int cents(Object value){try{return new BigDecimal(String.valueOf(value)).movePointRight(2).intValue();}catch(Exception ignored){return 0;}}
}
