package cn.naiblog.carsearch.wechat;
import cn.naiblog.carsearch.config.SettingService;import org.springframework.stereotype.Service;import tools.jackson.core.type.TypeReference;import tools.jackson.databind.ObjectMapper;import javax.crypto.Cipher;import javax.crypto.spec.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.util.*;
@Service public class WechatMessageCryptoService{private final SettingService settings;private final ObjectMapper mapper;private final SecureRandom random=new SecureRandom();public WechatMessageCryptoService(SettingService s,ObjectMapper m){settings=s;mapper=m;}
private Config config(){String token=settings.secure("wechat_message_token","");String aes=settings.secure("wechat_message_aes_key","");String app=settings.wechat().appId();if(!token.matches("[A-Za-z0-9]{3,32}")||!aes.matches("[A-Za-z0-9]{43}")||app.isBlank())throw new IllegalStateException("微信消息推送配置不完整");return new Config(token,aes,app);}
public boolean verify(String sig,String ts,String nonce){return MessageDigest.isEqual(signature(config().token,ts,nonce).getBytes(),sig.getBytes());}
public String echo(String encrypted,String sig,String ts,String nonce){Config c=config();if(!MessageDigest.isEqual(signature(c.token,ts,nonce,encrypted).getBytes(),sig.getBytes()))throw new IllegalArgumentException("微信消息地址验证签名失败");return decrypt(encrypted,c);}
public Map<String,Object> envelope(String body,String sig,String ts,String nonce)throws Exception{Map<String,Object>e=mapper.readValue(body,new TypeReference<LinkedHashMap<String,Object>>(){});String encrypted=String.valueOf(e.getOrDefault("Encrypt",e.getOrDefault("encrypt","")));Config c=config();if(!MessageDigest.isEqual(signature(c.token,ts,nonce,encrypted).getBytes(),sig.getBytes()))throw new IllegalArgumentException("微信消息签名校验失败");return mapper.readValue(decrypt(encrypted,c),new TypeReference<LinkedHashMap<String,Object>>(){});}
public Map<String,Object> response(Object value)throws Exception{Config c=config();String ts=String.valueOf(System.currentTimeMillis()/1000),nonce=HexFormat.of().formatHex(random.generateSeed(8)),encrypted=encrypt(mapper.writeValueAsString(value),c);return Map.of("Encrypt",encrypted,"MsgSignature",signature(c.token,ts,nonce,encrypted),"TimeStamp",ts,"Nonce",nonce);}
private String signature(String...parts){try{Arrays.sort(parts);return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-1").digest(String.join("",parts).getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
private byte[]key(Config c){return Base64.getDecoder().decode(c.aes+"=");}private String decrypt(String value,Config c){try{byte[]k=key(c),raw=Base64.getDecoder().decode(value);Cipher x=Cipher.getInstance("AES/CBC/NoPadding");x.init(Cipher.DECRYPT_MODE,new SecretKeySpec(k,"AES"),new IvParameterSpec(k,0,16));byte[]p=unpad(x.doFinal(raw));int n=ByteBuffer.wrap(p,16,4).getInt();String app=new String(p,20+n,p.length-20-n,StandardCharsets.UTF_8);if(!c.app.equals(app))throw new IllegalArgumentException("微信消息 AppID 校验失败");return new String(p,20,n,StandardCharsets.UTF_8);}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException("微信消息解密失败",e);}}
private String encrypt(String value,Config c)throws Exception{byte[]msg=value.getBytes(StandardCharsets.UTF_8),app=c.app.getBytes(StandardCharsets.UTF_8);ByteBuffer b=ByteBuffer.allocate(20+msg.length+app.length);b.put(random.generateSeed(16)).putInt(msg.length).put(msg).put(app);byte[]p=pad(b.array());byte[]k=key(c);Cipher x=Cipher.getInstance("AES/CBC/NoPadding");x.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(k,"AES"),new IvParameterSpec(k,0,16));return Base64.getEncoder().encodeToString(x.doFinal(p));}private byte[]pad(byte[]v){int n=32-v.length%32;byte[]p=Arrays.copyOf(v,v.length+n);Arrays.fill(p,v.length,p.length,(byte)n);return p;}private byte[]unpad(byte[]v){int n=v[v.length-1]&255;if(n<1||n>32)throw new IllegalArgumentException("微信消息填充无效");for(int i=v.length-n;i<v.length;i++)if((v[i]&255)!=n)throw new IllegalArgumentException("微信消息填充无效");return Arrays.copyOf(v,v.length-n);}private record Config(String token,String aes,String app){}
}
